Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/09/2022
Var
// Seção de Declarações das variáveis 
 F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("Qual é a temperatura onde você está? ")
 Leia (F)
 C <- (F-32)/1.8
 Escreva ("A temperatura em Celsius é: ", C)

Fimalgoritmo