Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/09/2022
Var
// Seção de Declarações das variáveis 
 Ano, Nascimento, Velas: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("Em que ano você nasceu? ")
 Leia (Nascimento)
 Ano <- 2022
 Velas <- (Ano-Nascimento)
 Escreva ("Você terá de usar ", Velas, " Velas.")
 
Fimalgoritmo