Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2022
Var
// Seção de Declarações das variáveis 
 Parcela, Valor: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("Digite o valor do produto que você irá comprar: R$")
  Leia (Valor)
 Parcela <- Valor/5
 Escreva ("O valor da parcela que você irá pagar é de: R$", Parcela)

Fimalgoritmo