Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2022
Var
// Seção de Declarações das variáveis 
 ValorF, ValorC: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("Insira o valor da temparatura em C: ")
  Leia (ValorC)
 ValorF <- (9*ValorC+160)/5
 Escreva ("A temperatura em F é: ", ValorF)

Fimalgoritmo